### ISSUE TITLE
Do we need to use `global` or can we test for `window`

### ISSUE THREAD

**Issue by nfrade** [atelier-saulx/based#137]
Scrumfun are using [Vite](https://vitejs.dev/) and they hit an issue [here](https://github.com/atelier-saulx/based/blob/main/packages/fetch/index.js#L1) because Vite does not expose global.

Can we guard this checking for `window` first?

![image](https://github.com/atelier-saulx/based/assets/683825/19c7cdb5-8f05-4a60-9bbf-65c1e85c969e)

**Comment by jimdebeer** [comment]
we can add it by default if it does not exist

**Comment by jimdebeer** [comment]
Ill take care of it
