### ISSUE TITLE
`stream` cannot work over a single POST request when using cloudflare

### ISSUE THREAD

**Issue by frammaa** [atelier-saulx/based#144]
Even though we are streaming the data, since the data is collected on a CF datacenter before it's forwarded to our own machines, it won't work unless we chunk it ourselves

**Comment by jimdebeer** [comment]
- [ ] protocol outgoing (register)
- [ ] store active streams per client
- [ ] protocol chunks
- [ ] start stream
- [ ] handle fileReader (browser)

**Comment by jimdebeer** [comment]
this does mean we dont support browser that do not have
https://caniuse.com/?search=fileReader
