### ISSUE TITLE
Can not filter on single reference

### ISSUE THREAD

**Issue by mstdokumaci** [atelier-saulx/based#43]
This filter on a many reference finds the item by the ceremony:
```
$filter: {
  $field: 'ceremonies',
  $operator: 'has',
  $value: 'ceTstStndp'
}
```

But this filter on a single reference can not find the item by the ceremony:
```
$filter: {
  $field: 'ceremony',
  $operator: '=',
  $value: 'ceTstStndp'
}
```

**Comment by OlliV** [comment]
`reference` and `references` fields are both handled internally like they were "semi-formal" sets (in the context of filtering) with different constraints, i.e. `reference` field is a set that can only have one member. Therefore, `has` should also work for the second case. Should it also/only support `=`, possibly.
